apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lenguyenkhang1904/argo.git
    targetRevision: HEAD
    path: argocd/app/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

