apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd-demo
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: marxkhang/sha256:e16c78af552a
        env:
          - name: USERNAME_DATABASE
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: DB_USERNAME

          - name: PASSWORD_DATABASE
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: DB_PASSWORD

          - name: URL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: URL_DATABASE

        ports:
        - containerPort: 8080
