apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: mypassword
